title: "Jus Mixed"
description: "It really is the best."
remote_theme: "mmistakes/so-simple-theme@3.2.0"
locale: en-US

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

google_analytics: G-84N0P9MSY1 # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: # site's Twitter username, e.g. "mmistakes"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

author:
  name: "Jus Mixed"
  picture: "/images/logo-jusmixed.png"  # Ganti dengan path gambar logo bisnis Anda jika ingin tampil di bio/footer
  email: "info@jusmixed.id"             # Ganti dengan email bisnis Anda
  twitter: "jusmixedID"                 # Username Twitter bila ada
  links:
    - title: "WhatsApp"
      url: "https://wa.me/628999563485"
      icon: "fab fa-whatsapp"
    - title: "GoFood"
      url: "https://gofood.co.id/jakarta/restaurant/jusmixed-id-xxxx"
      icon: "fas fa-utensils"
    - title: "ShopeeFood"
      url: "https://shopee.co.id/universitas/jusmixed-id-xxxx"
      icon: "fas fa-shopping-basket"
    - title: "YouTube"
      url: "https://youtube.com/@jusmixedid"
      icon: "fab fa-youtube"

footer_links:
  - title: "Feed"
    url: "atom.xml"
    icon: "fas fa-rss-square"
  - title: "WhatsApp"
    url: "https://wa.me/628999563485"
    icon: "fab fa-whatsapp"
  - title: "GoFood"
    url: "https://gofood.co.id/jakarta/restaurant/jusmixed-id-xxxx"
    icon: "fas fa-utensils"
  - title: "ShopeeFood"
    url: "https://shopee.co.id/universitas/jusmixed-id-xxxx"
    icon: "fas fa-shopping-basket"
  - title: "YouTube"
    url: "https://youtube.com/@jusmixedid"
    icon: "fab fa-youtube"
    
liquid:
  error_mode: strict

permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

search_full_content: false # Optional

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true
