title: "Jus Ceria"
description: "It really is the best."
remote_theme: "mmistakes/so-simple-theme@3.2.0"
locale: en-US

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: # site's Twitter username, e.g. "mmistakes"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

author:
  name: Jus Mixed
  picture:
  email:
  twitter:
  links:
    - title:
      url:
      icon:

footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square

liquid:
  error_mode: strict

permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

search_full_content: false # Optional

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true
